services:
  # Next.js Frontend
  app:
    build: ./next-js-app
    container_name: nextjs-app

  # Nest.js API
  nest-api:
    build: ./nest-api
    container_name: nest-api
    depends_on:
      ollama:
        condition: service_healthy # Waits for the healthcheck to pass

  # Custom Ollama LLM Service
  ollama:
    build: ./ollama-config
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - nest-api