services:
  # Next.js Frontend
  app:
    build: ./next-js-app
    container_name: nextjs-app
    restart: always

  # New Nest.js API
  nest-api:
    build: ./nest-api
    container_name: nest-api
    ports:
      - "4000:4000" # Exposes port 4000 for direct testing
    restart: always

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - nest-api
    restart: always
